accounts/urls.py
from django.urls import path
from accounts.views import *
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
app_name = 'accounts'


urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup_view, name='signup'),
    path('password_reset/', 
    auth_views.PasswordResetView.as_view(
        template_name='accounts/password_reset.html',
        email_template_name='accounts/password_reset_email.html',  
        success_url= reverse_lazy('accounts:password_reset_done')
    ), 
    name='password_reset'),
    
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html'
    ), name='password_reset_done'),
    
    path('reset/<uidb64>/<token>/', 
    auth_views.PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_confirm.html'
    ), 
    name='password_reset_confirm'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'
    ), name='password_reset_complete'),
    
]

blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed

app_name = "blog"


urlpatterns = [
    path("", blog, name="blog"),
    path('post-<int:pid>', blog_single, name='single'),
    path('category/<str:cat_name>', blog, name='category'),
    path('tag/<str:tag_name>', blog, name='tag'),
    path('author/<str:author_username>', blog, name='author'),
    path('search/', blog_search, name='search'),
    path("rss/feed/", LatestEntriesFeed())
]

mysite/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
import debug_toolbar
from debug_toolbar.toolbar import debug_toolbar_urls

sitemaps = {
    "static": StaticViewSitemap,
    'blog':BlogSitemap
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("website.urls")),
    path("blog/", include("blog.urls")),
    path('accounts/', include('accounts.urls')),
    path('', include('django.contrib.auth.urls')),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path('robots.txt', include('robots.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('captcha/', include('captcha.urls')),
    path('summernote/', include('django_summernote.urls'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
# Create your models here.

class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from accounts.models import SignUpForm
from django.contrib.auth.models import User
from django.contrib import messages

# Create your views here.
def login_view(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            identifier = request.POST.get('username')
            password = request.POST.get('password')

        
            if '@' in identifier:
                user_obj = User.objects.get(email=identifier)
                username = user_obj.username
            else:
                username = identifier

            user = authenticate(request, username=username, password=password)
            if user is not None:
                messages.add_message(request, messages.SUCCESS, 'your logged in successfully')
                login(request, user)
                return redirect('/')
            else:
                messages.add_message(request, messages.ERROR, 'something went wrong')
                return redirect('/')

        return render(request, 'accounts/login.html')
    else:
        return redirect('/')

@login_required
def logout_view(request):
    logout(request)
    return redirect('/')

def signup_view(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            username = request.POST.get('username')
            email = request.POST.get('email')
            password1 = request.POST.get('password1')
            password2 = request.POST.get('password2')
            
            if password1 != password2:
                messages.error(request, 'Passwords do not match.')
                return redirect('/')
            
            if User.objects.filter(username=username).exists():
                messages.error(request, 'Username already exists.')
                return redirect('/')
            
            if User.objects.filter(email=email).exists():
                messages.error(request, 'Email already registered.')
                return redirect('/')

            user = User.objects.create_user(username=username, email=email, password=password1)
            user.save()

            messages.success(request, 'You signed up successfully.')
            return redirect('/')
            
        
        return render(request, 'accounts/signup.html')
    else:
        return redirect('/')

templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Travel/Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
</head>
<body style="text-align: center;">
  {% if form.errors %}
  <div class="alert alert-danger">
    {% for field in form %}
      {% for error in field.errors %}
        <p>{{ error }}</p>
      {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
      <p>{{ error }}</p>
    {% endfor %}
  </div>
{% endif %}
    <form method="post" action="{% url 'accounts:login' %}" style="width: 300px; display: inline-block; margin-top: 100px; border: 1px black; border-radius: 20%;">
        <!-- Email input -->
        {% csrf_token %}
        
        <div data-mdb-input-init class="form-outline mb-4">
          <input placeholder="Username" name="username" type="text" id="form2Example1" class="form-control" />
          <label class="form-label" for="form2Example1">Usename or Email</label>
        </div>
      
        
        <div data-mdb-input-init class="form-outline mb-4">
          <input placeholder="Password" name="password" type="password" id="form2Example2" class="form-control" />
          <label class="form-label" for="form2Example2">Password</label>
        </div>
        
        <!-- 2 column grid layout for inline styling -->
        <div class="row mb-4">
          <div class="col d-flex justify-content-center">
            <!-- Checkbox -->
            <div class="form-check">
              <input class="form-check-input" type="checkbox" value="" id="form2Example31" checked />
              <label class="form-check-label" for="form2Example31"> Remember me </label>
            </div>
          </div>
      
          <div class="col">
            <!-- Simple link -->
            <a href="{% url 'accounts:password_reset' %}">Forgot password?</a>
          </div>
        </div>
      
        <!-- Submit button -->
        <button  type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-block mb-4">login</button>
      
        <!-- Register buttons -->
        <div class="text-center">
          <p>Not a member? <a href="#!">Register</a></p>
          <p>or log in with:</p>
          <button  type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1">
            <i class="fab fa-facebook-f"></i>
          </button>
      
          <button  type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1">
            <i class="fab fa-google"></i>
          </button>
      
          <button  type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1">
            <i class="fab fa-twitter"></i>
          </button>
      
          <button  type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1">
            <i class="fab fa-github"></i>
          </button>
        </div>
      </form>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
</html>

templates/accounts/password_reset.html
<h2>Forgot your password?</h2>
<p>Enter your email address and we'll send you instructions.</p>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Send</button>
</form>

templates/accounts/password_reset_complete.html
<p>Your password has been set. You may <a href="{% url 'accounts:login' %}">log in now</a>.</p>

templates/accounts/password_reset_confirm.html
<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Change my password</button>
</form>

templates/accounts/password_reset_done.html
<p>We’ve emailed you instructions for setting your password.</p>

templates/accounts/password_reset_email.html
{% autoescape off %}
Hi {{ user.get_username }},
Please click the link below to reset your password:

{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
If you didn't request this, please ignore this email.
{% endautoescape %}

templates/accounts/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Travel/Signup</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
</head>
<body style="text-align: center;">
    
    <form method="post" action="{% url 'accounts:signup' %}" style="width: 300px; display: inline-block; margin-top: 100px; border: 1px black; border-radius: 20%;">
        <!-- Email input -->
        {% csrf_token %}
        <div data-mdb-input-init class="form-outline mb-4">
          <input placeholder="Username" name="username" type="text" id="form2Example1" class="form-control" />
          <label class="form-label" for="form2Example1">Usename</label>
        </div>
        <div data-mdb-input-init class="form-outline mb-4">
          <input placeholder="Email" name="email" type="email" id="form2Example1" class="form-control" />
          <label class="form-label" for="form2Example1">Email</label>
        </div>
        <div data-mdb-input-init class="form-outline mb-4">
          <input placeholder="Password" name="password1" type="password" id="form2Example2" class="form-control" />
          <label class="form-label" for="form2Example2">Password</label>
        </div>
        <div data-mdb-input-init class="form-outline mb-4">
          <input placeholder="Password" name="password2" type="password" id="form2Example2" class="form-control" />
          <label class="form-label" for="form2Example2">Confirm Password</label>
        </div>
        
        <!-- 2 column grid layout for inline styling -->
        <div class="row mb-4">
          <div class="col d-flex justify-content-center">
            <!-- Checkbox -->
            <div class="form-check">
              <input class="form-check-input" type="checkbox" value="" id="form2Example31" checked />
              <label class="form-check-label" for="form2Example31"> Remember me </label>
            </div>
          </div>
      
          
        </div>
      
        <!-- Submit button -->
        <button  type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-block mb-4">signup</button>
      
        <!-- Register buttons -->
        <div class="text-center">
          <p>Not a member? <a href="#!">Register</a></p>
          <p>or sign up with:</p>
          <button  type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1">
            <i class="fab fa-facebook-f"></i>
          </button>
      
          <button  type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1">
            <i class="fab fa-google"></i>
          </button>
      
          <button  type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1">
            <i class="fab fa-twitter"></i>
          </button>
      
          <button  type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1">
            <i class="fab fa-github"></i>
          </button>
        </div>
      </form>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
</html>